### ISSUE TITLE
Use JSON instead of YAML for configuration file

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#74]
This projected is targeted at folks working near the front end. Besides being a better format IMHO, I think that JSON will be more familiar to these people. I think we should switch to JSON to lower the barrier to entry, just a little bit.

**Comment by trotzig** [comment]
Sounds like a good idea, though we have to figure out how to do work around doing dynamic configuration like this:

```yaml
port: <%= 7654 + ENV['EXECUTOR_NUMBER'].to_i %>
source_files:
  - http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
  - public/assets/diffux_ci.js
s3_access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
s3_bucket_name: diffux_ci-diffs
snapshots_folder: ./tmp/diffux-snapshots-ci
```

This is what `.diffux.yaml` looks like for us at the moment.
